# Generated by Django 5.2 on 2025-04-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extracted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='txt_file',
            field=models.FileField(blank=True, null=True, upload_to='texts/'),
        ),
    ]
